#!/usr/bin/env python3
"""Regenerates test/fixtures/fixtures.h from the .json fixture files in this
directory, embedding each as a C++ raw string literal. Run from the repo root:
    python3 test/fixtures/generate_fixtures_h.py
"""
import pathlib

FIXTURES = [
    ("kFixtureDialFlights", "dial_flights.json"),
    ("kFixtureHaLightOffice", "ha_light_office_2026-09-04.json"),
    ("kFixtureHaLightLamp", "ha_light_lamp_2026-09-04.json"),
]


def main():
    fixtures_dir = pathlib.Path(__file__).parent
    out = [
        "#pragma once",
        "",
        "// Generated by test/fixtures/generate_fixtures_h.py from the .json files in this",
        "// directory. Regenerate with: python3 test/fixtures/generate_fixtures_h.py",
        "// Do not hand-edit; edit the source .json fixture and regenerate instead.",
        "",
    ]
    for name, filename in FIXTURES:
        text = (fixtures_dir / filename).read_text()
        assert ")json" not in text, f"{filename} contains the raw-string delimiter"
        out.append(f'static const char {name}[] = R"json({text})json";')
        out.append("")

    (fixtures_dir / "fixtures.h").write_text("\n".join(out))
    print("wrote", fixtures_dir / "fixtures.h")


if __name__ == "__main__":
    main()
